services:
  test-database-mouts:
    image: postgres:16-alpine
    volumes:
      - test-data-mouts:/var/lib/postgresql/data
    env_file:
      - ../config/.e2e.env
    networks:
      - test-network-mouts
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  test-cache-mouts:
    image: redis:7-alpine
    networks:
      - test-network-mouts
    ports:
      - "6379"
    volumes:
      - test-cache-data-mouts:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  test-api-mouts:
    build:
      context: ..
      dockerfile: docker/e2e.Dockerfile
    env_file:
      - ../config/.e2e.env
    networks:
      - test-network-mouts
    ports:
      - "3001:3001"
    depends_on:
      test-cache-mouts:
        condition: service_healthy
      test-database-mouts:
        condition: service_healthy

volumes:
  test-cache-data-mouts:
  test-data-mouts:

networks:
  test-network-mouts:
    driver: bridge