services:
  database-mouts:
    image: postgres:16-alpine
    volumes:
      - data-mouts:/var/lib/postgresql/data
    env_file:
      - ../config/.env
    networks:
      - network-mouts
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  cache-mouts:
    image: redis:7-alpine
    networks:
      - network-mouts
    ports:
      - "6379:6379"
    volumes:
      - cache-data-mouts:/data

volumes:
  data-mouts:
  cache-data-mouts:

networks:
  network-mouts:
    driver: bridge
